sudo: false
language: node_js
node_js: 12
install: echo "Installation happens in the setup script"
addons:
  apt:
    packages:
      # cypress told me I need it: https://docs.cypress.io/guides/guides/continuous-integration.html#Travis
      - libgconf-2-4
cache:
  npm: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache
notifications:
  email: false
branches:
  only:
    - master
script:
  - npm run setup
after_success:
  - npx codecov
