# build environment
FROM node:12.16 as build

WORKDIR /picd-app
ENV PATH /picd-app/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./
RUN npm ci --silent
RUN npm install react-scripts@3.4.0 -g --silent

COPY . ./
RUN npm run-script build

# production environment
FROM nginx:stable-alpine
COPY --from=build /picd-app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
