version: '3.7'

services:

##################################
# Setup Node API Container       #
##################################
  picd-server:
    container_name: picd-server
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    image: gcr.io/endpoints-release/picd-server:${VERSION}
    environment:
      SERVER_HOST: ${SERVER_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}

##################################
# Setup REACT Client Container   #
##################################
  picd-client:
    container_name: picd-app
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    image: gcr.io/teacher-student-forum/picd-app:${VERSION}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    depends_on:
      - picd-server