version: "3.8"

x-common-variables: &common-variables
  MYSQL_USER: picd
  MYSQL_PASSWORD: picdcapstone
  MYSQL_DATABASE: picd

  REACT_APP_NAME: "PICD"
  REACT_APP_CIPHER: ThisIsThePicdProjectReallyLongAndSecureKey
  REACT_APP_IV_KEY: myIVKey_DoYouThinkThisIsSecureEnoughQuestionMark
  APP_SERVER_PORT: 9000
  REACT_APP_PORT: 3000

services:

  # MySql server service settings
  mysql:
    container_name: picd-mysql
    image: mysql:5.6
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/insert_data.sql:/docker-entrypoint-initdb.d/insert_data.sql
      - dbdata:/var/lib/mysql
  
  # PHP My Admin service settings
  phpmyadmin:
    container_name: picd-phpmyadmin
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    links:
      - mysql:mysql
    ports:
      - 8080:80
    restart: always
  
  # API service settings
  api:
    container_name: picd-api
    image: docker.pkg.github.com/s3539822/picd-capstone/picd-api:beta-1.1
    build:
        context: ./api
        dockerfile: Dockerfile.prod
    depends_on:
      - mysql
    expose:
      - 9000
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql
      MYSQL_PORT: 3306
    ports:
      - 9000:9000
    volumes:
      - ./api:/app
      - apidata:/app/public/media
    links:
      - mysql
  
  # Client service settings
  client:
    container_name: picd-client
    image: docker.pkg.github.com/s3539822/picd-capstone/picd-client:beta-1.1
    build:
        context: ./api
        dockerfile: Dockerfile.prod
    environment:
      <<: *common-variables
      REACT_APP_API_SERVER_ADDRESS: http://localhost:9000
    expose:
      - 80
    ports:
      - 80:80
    volumes:
      - ./client/src:/app/src
    links:
      - api

volumes:
  dbdata:
  apidata: