Use picd;

DROP TABLE IF EXISTS file;
DROP TABLE IF EXISTS version;
DROP TABLE IF EXISTS stage;
DROP TABLE IF EXISTS user_has_project;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS clearance;
DROP TABLE IF EXISTS project;