# pull official base image
FROM node:12.16 as build

# set working directory
RUN mkdir -p /app
WORKDIR /app

# get app dependencies
COPY package.json ./app
COPY package-lock.json ./app

# add app
COPY . /app

# install app dependencies
RUN npm install --silent


FROM node:latest

WORKDIR /app
COPY --from=build /app/node_modules /app/node_modules

COPY . /app

# start app
CMD ["npm", "run", "start:prod"]